### ISSUE TITLE
Add ability to specify an include filter for the files to be purged

### ISSUE THREAD

**Issue by tripodsan** [koraa/hlx-gh-action-purge-updated-cache#2]
suggest an input property 'include':

```yaml
on: push

jobs:
  ci_trigger:
    runs-on: ubuntu-latest
    name: Clear helix pages cache
    steps:
      - name: Trigger
        id: trigger
        uses: adobe-rnd/github-purge-cache-action@master
        with:
          repo-token: ${{ secrets.MY_GITHUB_TOKEN }}
          include:
            - /scripts*
            - /styles*
```

the filtering should use https://www.npmjs.com/package/glob
